### ISSUE TITLE
#8 Login/Logout :Security

### ISSUE THREAD

**Issue by dt222cc** [rn222cx/1DV450_rn222cx#11]
A security hole in the application that I found out from the peer-review on my application. When you are logged in and then log out and press the back button, the previous page prior to the log out gets presented. For example, the user has domain side in front (with API keys), log out and then leave your computer without leaving the page or closing the browser, another person can access the information on that page, just by testing to click the back button.

The solution that I have to offer was shared with me by mv222fp / Marco30. It prevents caching by adding the following in the Application Controller and adding "data: {no_turbolink: true}" in the logout link.

The link in app/views/layouts/_header.html.erb

```
<%= link_to "Log out", logout_path, data: {no_turbolink: true}, class: "nav-link-right" %>
```

In app/controllers/application_controller.rb

```
before_action :no_cache

def no_cache
  response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  response.headers["Pragma"] = "no-cache"
  response.headers["Expires"] = "Fri, 09 Jan 2004 00:00:00 GMT"
end
```

**Comment by rn222cx** [comment]
Riktigt bra åtgärd. Fixed
