### ISSUE TITLE
Problem att sätta upp databasen

### ISSUE THREAD

**Issue by RebeccaFransson** [rn222cx/1DV450_rn222cx#13]
Kunde inte sätta upp databasen. När jag körde `rake db:migrate` fick jag ett error: “TZInfo::DataSourceNotFound”. Det visade sig att du använder dig utav ett gem eller ett bibliotek som behöver TZInfo för att fungera korrekt, detta error uppkommer oftast på windows datorner, vilket jag sitter på. Jag löste detta genom att lägga till `gem 'tzinfo-data'` i din gem-fil.

**Comment by rn222cx** [comment]
Kan stämma då jag sitter på en mac. jag kommer lägga in det som kommentar i min gem fil för windows användare.
