### ISSUE TITLE
rake db:migrate -> rake db:schema:load

### ISSUE THREAD

**Issue by RebeccaFransson** [rn222cx/1DV450_rn222cx#14]
Vissa programmerare säger att använda sig utav `$ rake db:migrate` är ett dåligt exempel när man skapar applikationen på ett annat system. Istället borde man använda sig utav `$ rake db:schema:load`. Det står mer om detta i din fil db/schema.rb.

**Comment by rn222cx** [comment]
Efter lite googlande så passar det best med $ rake db:schema:load i detta ändamålet.
