### ISSUE TITLE
Hatoeas

### ISSUE THREAD

**Issue by RebeccaFransson** [rn222cx/1DV450_rn222cx#15]
I din readme förstod jag att du har problem med hateoas och att länka vidare på localhost, det hade varit kul om du hade lagt ut den live eller något så jag på något sätt hade kunnat se lite hatoas.
Själv har jag använt mig utav sterializers som tillåter mig att utforma responsen så som jag vill. Här var den enkelt för mig att inkludera länkar och länka vidare till objekt som hade en relation till det efter frågande objektet.

**Comment by rn222cx** [comment]
Ett exempel för ej subdomän användare skapad för peer reviews. (se senaste commit)
