### ISSUE TITLE
Slutanvändare och användare utav apiet

### ISSUE THREAD

**Issue by RebeccaFransson** [rn222cx/1DV450_rn222cx#16]
Du har också bara en user-model. Det skall väl finnas en modell för slutanvändarna och en modell för användarna utav api:et?

**Comment by rn222cx** [comment]
I dagens läge är alla amvändare i samma model/tabell. Tanken är att försöka dela upp detta i tredje labben när jag har fått en bättre förståelse/helhet av applikationen.
