### ISSUE TITLE
Positiv feedback

### ISSUE THREAD

**Issue by RebeccaFransson** [rn222cx/1DV450_rn222cx#17]
Jag ser att du helt klar är mycket duktigare än mig. Därför har det varitextra svårt att hjälpa dig förbättra din kod.
Det är super bra att du har namnen på dina användare i urlen istället för id.
Din postman ser också bra ut.
Riktigt bra search-funktion.
Samt en ordentlig metod för att hantera roller, smart med Policy.
Jag har lärt min en hel del utav din kod iallafall. Hoppas du får ett bra betyg!

**Comment by rn222cx** [comment]
Tack, väldigt fin feedback :)
