### ISSUE TITLE
#Peer-Review-1.0

### ISSUE THREAD

**Issue by dt222cc** [rn222cx/1DV450_rn222cx#7]
<h2>Intro</h2>

The work on the next step, API, has already been started.
I'll do my review on the registration part.

I also have been adding separate issues to isolate the tasks.

<h2>Feature</h2>
- [ ] It is/was possible to register an user without specifying an username.
- [ ] The order of error messages on signup attempts is/was out of order.
- [ ] Perhaps re-apply password if you want to alter user settings.
- [ ] Should an user be able to login and signup even if an user is "logged in"?
- [ ] Able to create domains with the same name, ignore this if intended.
- [ ] I'm not able to delete an users own domain, only as admin, the user gets redirected to the login page on delete attempt.
- [ ] Broken session: User could use the back button to access the content of the previous page prior to the logout, if the user did not do any action after the logout.
- [ ] User could try to login with blank fields, response: "Email doesn't exist"

<h2>Code</h2>

Good naming and indentation.
Plenty of trailing whitespaces in the code (bad).
Empty lines between code, consistency.
Lack of comments.

<h2>Bonus</h2>

Has some tests, which passes.
Has Seeds to populate database.
No problems with installing and setting up the app.

<h2>View</h2>

Title text is not aligned with the rest of the content.
If you minimize the window some text gets covered by the navbar.
Shortcut for user profile in the navbar?

**Comment by rn222cx** [comment]
Många bra problemlösningar det tackar jag för =)

**Comment by rn222cx** [comment]
Många bra problemlösningar det tackar jag för =)
